version: '2'

services:
  minio:
    image: 'bitnami/minio:latest'
    ports:
      - '9000:9000'
      - '9001:9001'
    environment:
      - MINIO_ROOT_USER=admin
      - MINIO_ROOT_PASSWORD=12345678
    command: minio server /bitnami/minio/data --console-address :9001
    volumes:
      - minio-persistence:/bitnami/minio/data
  mc:
    image: 'minio/mc'
    depends_on:
      - minio
    container_name: mcbkp
    entrypoint: >
      /bin/sh -c "
      echo /usr/bin/mc config host a src https://play.minio.io:9000 $${PLAY_ACCESS_KEY} $${PLAY_SECRET_KEY};
      /usr/bin/mc config host a src https://play.minio.io:9000 $${PLAY_ACCESS_KEY} $${PLAY_SECRET_KEY};
      /usr/bin/mc config host a bkp http://minio:9000 $${MINIO_ACCESS_KEY} $${MINIO_SECRET_KEY};
      /usr/bin/mc mirror -w src bkp;
      "
  postgres:
    image: 'postgres'
    ports:
      - '5432:5432'
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=12345678
      - PGDATA=/var/lib/postgresql/data/pgdata
    volumes:
      - postgres-data:/var/lib/postgresql/data
  nginx:
    image: nginx
    volumes:
      - ./nginx-content:/var/www/html
    ports:
      - "8081:80"
    environment:
      - NGINX_HOST=sebereu.com
      - NGINX_PORT=80
      - COPY static-html-directory /usr/share/nginx/html
volumes:
  minio-persistence:
  postgres-data:
  nginx-content:
